apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zerocloud
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: zerocloud
    spec:
      containers:
        - name: zerocloud
          image: anishnath/0cloud0
          ports:
			- containerPort: 8080
	      envFrom:
			- configMapRef:
	          name: zerocloud-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: zerocloud
  labels:
    name: zerocloud
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: zerocloud
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: zeroclouddeploy
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: 0cloud0.com
    http:
      paths:
      - path: /
        backend:
          serviceName: zerocloud
          servicePort: 8080