CREATE TABLE users (
    id INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
    username NVARCHAR(120)  NULL,
    quota INTEGER DEFAULT 3,
    Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE users_data (
    id INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
    username NVARCHAR(120)  NULL,
    docker_image NVARCHAR(50) NOT  NULL,
    expose_port  NVARCHAR(40)   NULL,
    expose_url  NVARCHAR(40)   NULL,
    status  NVARCHAR(40)  DEFAULT NOTDEPLOYED,
    Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(id) REFERENCES users(username)
);